# Deploy artifact in azure vm
# we have configure agent in same vm
# pipeline running in same vm

# name: CI/CD Pipeline

# on: workflow_dispatch
  # push:
  #   branches:
  #     - main
 
# jobs:
#   deploy:
#     runs-on: self-hosted
#     steps:
#       - name: checkout repo
#         uses: actions/checkout@v4

#       - name: install nginx
#         run: |
#           sudo apt update
#           sudo apt install nginx -y      

#       - name: start and enable nginx   
#         run: |
#           sudo systemctl start nginx
#           sudo systemctl enable nginx

#       - name: deploy to nginx
#         run: |
#           sudo rm -rf /var/www/html/*
#           sudo cp -r StreamFlix/* /var/www/html/

#       - name: Restart Nginx
#         run: sudo systemctl restart nginx     


##################################################################################
# Deploye artifact in azure vm
# runner- github hosted

name: Deploy Website

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Copy website to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt purge nginx nginx-common -y
            sudo apt autoremove -y
            sudo nginx -v
            sudo apt update
            sudo apt install nginx -y
            sudo systemctl start nginx
            sudo systemctl enable nginx
          source: "StreamFlix/*"
          target: "/var/www/html"
          strip_components: 1

      # - name: Deploy on VM
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.VM_HOST }}
      #     username: ${{ secrets.VM_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       sudo apt purge nginx nginx-common -y
      #       sudo apt autoremove -y
      #       sudo nginx -v
      #       sudo apt update
      #       sudo apt install nginx -y
      #       sudo systemctl start nginx
      #       sudo systemctl enable nginx
      #       sudo rm -rf /var/www/html/*
      #       sudo cp -r /tmp/streamflix/StreamFlix/* /var/www/html/
      #       sudo systemctl restart nginx

            

